class DataIngestionArtifact:...


# ""..."" means pass
class DataValidationArtifact:...

class DataTransformationArtifact:...


class ModelTrainerArtifact:...

class ModelEvaluationArtifact:...
class ModelPusherArtifact:...