class DataIngestionConfig:...


# ""..."" means pass
class DataValidationConfig:...

class DataTransformationConfig:...


class ModelTrainerConfig:...

class ModelEvaluationConfig:...
class ModelPusherConfig:...

